controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute   
api:
    path: /api/
    controller: App\Controller\AuthController::api
login_check:
    path:     /login_check
    methods:  [POST]


